Fix error_message method
Not all calls of this method have a error.response which was triggering:

```
NoMethodError: undefined method `[]' for nil
from /govuk/govuk-chat/lib/answer_composition/openai_answer.rb:39:in `error_message'
Caused by OpenAIClient::RequestError: Failed to open TCP connection to api.openai.com:443 (getaddrinfo: Name or service not known)
from /root/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1603:in `initialize'
Caused by Faraday::ConnectionFailed: Failed to open TCP connection to api.openai.com:443 (getaddrinfo: Name or service not known)
from /root/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1603:in `initialize'
Caused by Socket::ResolutionError: Failed to open TCP connection to api.openai.com:443 (getaddrinfo: Name or service not known)
from /root/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1603:in `initialize'
Caused by Socket::ResolutionError: getaddrinfo: Name or service not known
from /root/.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/net-http-0.4.1/lib/net/http.rb:1603:in `initialize'
```