Raise InvalidToolCallError when the LLM tool usage is invalid
This commit adds the InvalidToolCallError to the BedrockOpenAIOssInvoke
class. It is raised when the LLM response either:

- doesn't return valid JSON (JSON::ParserError)
- doesn't conform to the expected schema ( JSON::Schema::ValidationError)
- doesn't include tool call arguements in the response

The latter was causing the following error to be raised on sentry when
the LLM didn't use the provided tool:

```
undefined method '[]' for nil (NoMethodError)
choice["message"]["tool_calls"][0]["function"]["arguments"]
                               ^^^
```

To handle this it now digs into the response to check if the tool call arguments
are present, and raises the InvalidToolCallError if not.

A rescue has been added to catch the other 2 errors. We then raise the
InvalidToolCallError with a message that includes the original error message
so we can see the specific reason why the tool call was invalid in sentry.

Consumers of the BedrockOpenAIOssInvoke class can then choose to rescue the
InvalidToolCallError and handle it as needed. For now i've only added a
resuce to the "generate_topics_for_question" rake task, but in a subsequent
PR we will remove it from the rake task it and add it to the classes that
call the BedrockOpenAIOssInvoke class. So that'll be:

- AutoEvaluation::TopicTagger
- AutoEvaluation::Coherence
- AutoEvaluation::AnswerRelevancy
- AutoEvaluation::Faithfulness
- AutoEvaluation::ContextRelevancy