Move committee to be a runtime dependency
We use committee for validating responses outside of the dev and test
environments and thus need it available to all environments.

This fixes the app failing to deploy with:

```
-----> Preparing app for Rails asset pipeline
cp: warning: behavior of -n is non-portable and may change in future; use --update=none instead
       Running: rake assets:precompile
       rake aborted!
       LoadError: cannot load such file -- committee (LoadError)
       /tmp/build_9036a223/vendor/bundle/ruby/3.4.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in 'Kernel#require'
       /tmp/build_9036a223/vendor/bundle/ruby/3.4.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in 'Kernel#require'
       /tmp/build_9036a223/config/initializers/committee.rb:1:in '<main>'
```