Add dalli to gemfile
We recently added a memcache to our application https://github.com/alphagov/govuk-chat/pull/834
and we're seeing an error in argo

```
INFO: with_tmpdir_for_ruby: execing rails with TMPDIR=/tmp/ruby-app-KPnS4uhQ
You don't have dalli installed in your application. Please add it to your Gemfile and run bundle install
bin/rails aborted!
Could not find cache store adapter for mem_cache_store (cannot load such file -- dalli)
/app/config/environment.rb:5:in `<main>'

Caused by:
LoadError: cannot load such file -- dalli (LoadError)
/app/config/environment.rb:5:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

Rails says that dalli is automatically included as a dependency via
Rails https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-memcachestore.

I can see "opentelemetry-instrumentation-dalli (~> 0.25.0)" in the Gemfile.lock.
I'm going to add dalli to the Gemfile to make it explicit to see if it
resolves the issue.