Be resilient to magic links from unsubscribed users
Users can be deleted, either by unsubscribing or through the admin area,
when this occurs any Passwordless::Session values for that user id will
still exist and now reference an EarlyAccessUser who does not exist.

Thus if a user attempts to use that magic link (which they really
shouldn't since they probably did the unsubscribing themselves) they'll
get a 500 error of:

```
undefined method `sign_in' for nil (NoMethodError)

      early_access_user.sign_in(passwordless_session)
                       ^^^^^^^^
```

This does a check before proceeding that authenticatable exists.

An alternative approach could be to delete each Passwordless::Session
when a user is deleted though I decided to go this way as there aren't
database guarantees on the authenticatable association and I feared
doing that deletion could be potentially a slow operation.

Sentry issue: https://govuk.sentry.io/issues/6088625395/events/9ce2cde8a8ef4bd5ae43b1a4f55a37a2/?project=4507072589070336&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=next-event&statsPeriod=90d&stream_index=5