Refactor of JS code to manage 2 message lists
This sets up a module, ConversationMessageLists, which is used for
handling all of the managing of the message list elements.

This is a somewhat unusual GOV.UK module in that it is initialised
manually rather than using a data attribute to initialise. It could be
that because of this we don't want to consider this code a "module" but
as module is such a generic term I thought it'd be fine.

It pulls in code from https://github.com/alphagov/govuk-chat/pull/441
for both managing the two lists and the progressive disclosure handling
to avoid needing to duplicate code in other places of the JS or
expanding responsibilities of existing modules.

It has a few minor consistency fixes such as using classes for template
selectors rather than ids.

I did find myself caught into a huge challenge with selenium state
elements when running the tests on the CLI, example below. It was
related to the haveClass matcher, I was able to resolve it by switching
to a `expect(element.classList).toContain` after a long tedious battle.

```
.....JavascriptError: javascript error: {"status":10,"value":"stale element not found in the current frame"}
  (Session info: chrome=127.0.6533.120)
    at Object.throwDecodedError (/Users/kevin.dew/govuk/govuk-chat/node_modules/selenium-webdriver/lib/error.js:521:15)
    at parseHttpResponse (/Users/kevin.dew/govuk/govuk-chat/node_modules/selenium-webdriver/lib/http.js:514:13)
    at Executor.execute (/Users/kevin.dew/govuk/govuk-chat/node_modules/selenium-webdriver/lib/http.js:446:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (/Users/kevin.dew/govuk/govuk-chat/node_modules/selenium-webdriver/lib/webdriver.js:740:17) {
  remoteStacktrace: '0   chromedriver                        0x0000000104705024 cxxbridge1$str$ptr + 1887276\n' +
    '1   chromedriver                        0x00000001046fd700 cxxbridge1$str$ptr + 1856264\n' +
    '2   chromedriver                        0x000000010430c82c cxxbridge1$string$len + 88524\n' +
    '3   chromedriver                        0x00000001043117f8 cxxbridge1$string$len + 108952\n' +
    '4   chromedriver                        0x00000001043132d4 cxxbridge1$string$len + 115828\n' +
    '5   chromedriver                        0x0000000104388fc4 cxxbridge1$string$len + 598372\n' +
    '6   chromedriver                        0x000000010438848c cxxbridge1$string$len + 595500\n' +
    '7   chromedriver                        0x0000000104345474 cxxbridge1$string$len + 321044\n' +
    '8   chromedriver                        0x00000001043460e4 cxxbridge1$string$len + 324228\n' +
    '9   chromedriver                        0x00000001046cca08 cxxbridge1$str$ptr + 1656336\n' +
    '10  chromedriver                        0x00000001046d1464 cxxbridge1$str$ptr + 1675372\n' +
    '11  chromedriver                        0x00000001046b28ec cxxbridge1$str$ptr + 1549556\n' +
    '12  chromedriver                        0x00000001046d1c14 cxxbridge1$str$ptr + 1677340\n' +
    '13  chromedriver                        0x00000001046a45fc cxxbridge1$str$ptr + 1491460\n' +
    '14  chromedriver                        0x00000001046eea5c cxxbridge1$str$ptr + 1795684\n' +
    '15  chromedriver                        0x00000001046eebd8 cxxbridge1$str$ptr + 1796064\n' +
    '16  chromedriver                        0x00000001046fd334 cxxbridge1$str$ptr + 1855292\n' +
    '17  libsystem_pthread.dylib             0x0000000187f4df94 _pthread_start + 136\n' +
    '18  libsystem_pthread.dylib             0x0000000187f48d34 thread_start + 8\n'
}
```

Co-authored-by: Daniel Karaj <daniel.karaj@digital.cabinet-office.gov.uk>
Co-authored-by: Jon Kirwan <87758239+jon-kirwan@users.noreply.github.com>